# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Packages
      run: CI=false npm install
    - name: Build from source
      run: CI=false npm run build

    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.USERNAME}}
        git remote add origin https://${{secrets.USERNAME}}:${{secrets.PASSWORD}}@github.com/${{secrets.USERNAME}}/project.git
        CI=false npm run deploy
